# Site settings
title: '华思尧的备忘录' # Your Title
tagline: '坚持，执着，追随内心' # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: redcarpet
highlighter: pygments
baseurl: #/strange_case # the subpath of your site, e.g. /blog/
