# Site settings
title: "Aggregate Thoughts" # Your Title
tagline: "Just figure out what's next." # A brief tagline for your site
sidebar_image: /images/cover.jpg

# Build settings
markdown: kramdown
highlighter: Rouge
baseurl: #/strange_case # the subpath of your site, e.g. /blog/
